application: warren-r-bank
version: sumome
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  mime_type: image/x-icon
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/(.*\.json)
  mime_type: application/json
  static_files: static/\1
  upload: static/(.*\.json)
  expiration: "1h"

- url: /static
  static_dir: static

- url: /list_builder_redirect
  script: list_builder_redirect.php

- url: .*
  mime_type: text/html
  static_files: index.html
  upload: index\.html
